from pathlib import Path
import requests
import yaml

SOURCES = {
    "OpenAI": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml",
    "Gemini": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.yaml",
    "Copilot": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.yaml",
}

OUTPUT = Path("ai.yaml")


def fetch_yaml(url: str) -> dict:
    resp = requests.get(url, timeout=30)
    resp.raise_for_status()
    data = yaml.safe_load(resp.text)
    if not isinstance(data, dict):
        raise ValueError(f"Invalid YAML format from {url}")
    return data


def normalize_payload(data: dict) -> list[str]:
    payload = data.get("payload", [])
    if not isinstance(payload, list):
        raise ValueError("payload is not a list")
    result = []
    for item in payload:
        if isinstance(item, str):
            item = item.strip()
            if item:
                result.append(item)
    return result


def dedupe_keep_order(items: list[str]) -> list[str]:
    seen = set()
    out = []
    for item in items:
        if item not in seen:
            seen.add(item)
            out.append(item)
    return out


def main():
    merged = []
    source_count = {}

    for name, url in SOURCES.items():
        data = fetch_yaml(url)
        payload = normalize_payload(data)
        source_count[name] = len(payload)
        merged.extend(payload)

    merged = dedupe_keep_order(merged)

    output = {
        "payload": merged
    }

    header = [
        "# This file is auto-generated by GitHub Actions.",
        "# Source repository: blackmatrix7/ios_rule_script",
        "# Included rules: OpenAI, Gemini, Copilot",
        "# Do not edit manually.",
        "",
    ]

    OUTPUT.write_text(
        "\n".join(header) + yaml.safe_dump(output, allow_unicode=True, sort_keys=False),
        encoding="utf-8"
    )

    print("Generated ai.yaml")
    print("Source item counts:", source_count)
    print("Merged item count:", len(merged))


if __name__ == "__main__":
    main()
